[[actor]]
name= "Minion1"
position="left"

[[actor]]
name= "Minion2"
position="right"


[[dialog]]
speaker= "Minion1"
emote= "drops"
fr= "J'avais envie de faire une sieste. Je me demande pourquoi il nous a choisis pour cette mission."
en= "I wanted to take a nap. I wonder why he chose us for this mission."
[[dialog]]
speaker= "Minion2"
fr= "Ouais, le Sorcier est vraiment strict. Mais on doit protéger les cristaux."
en= "Yeah, the Wizard is really strict. But we must protect the crystals."
[[dialog]]
speaker= "Minion1"
fr= "Le Sorcier n'avait pas dit qu'il allait créer des monstres pour garder ces trucs ? C'est quoi, au juste, un cristal ?"
en= "Didn't the Wizard say he would create some monsters to guard those things? What's a crystal anyway?"
[[dialog]]
speaker= "Minion2"
fr= "Je sais pas, peut-être un truc qu'il a ramené du monde des humains ?"
en= "I don't know, maybe something he got from the human world?"