// export const imgs = [
// 	'Keyboard/0_Key_Light',
// 	'Keyboard/10_Key_Light',
// 	'Keyboard/11_Key_Light',
// 	'Keyboard/12_Key_Light',
// 	'Keyboard/1_Key_Light',
// 	'Keyboard/2_Key_Light',
// 	'Keyboard/3_Key_Light',
// 	'Keyboard/4_Key_Light',
// 	'Keyboard/5_Key_Light',
// 	'Keyboard/6_Key_Light',
// 	'Keyboard/7_Key_Light',
// 	'Keyboard/8_Key_Light',
// 	'Keyboard/9_Key_Light',
// 	'Keyboard/A_Key_Light',
// 	'Keyboard/Alt_Key_Light',
// 	'Keyboard/Arrow_Down_Key_Light',
// 	'Keyboard/Arrow_Left_Key_Light',
// 	'Keyboard/Arrow_Right_Key_Light',
// 	'Keyboard/Arrow_Up_Key_Light',
// 	'Keyboard/Asterisk_Key_Light',
// 	'Keyboard/B_Key_Light',
// 	'Keyboard/Backspace_Alt_Key_Light',
// 	'Keyboard/Backspace_Key_Light',
// 	'Keyboard/Bracket_Left_Key_Light',
// 	'Keyboard/Bracket_Right_Key_Light',
// 	'Keyboard/C_Key_Light',
// 	'Keyboard/Caps_Lock_Key_Light',
// 	'Keyboard/Command_Key_Light',
// 	'Keyboard/Ctrl_Key_Light',
// 	'Keyboard/D_Key_Light',
// 	'Keyboard/Del_Key_Light',
// 	'Keyboard/E_Key_Light',
// 	'Keyboard/End_Key_Light',
// 	'Keyboard/Enter_Alt_Key_Light',
// 	'Keyboard/Enter_Key_Light',
// 	'Keyboard/Enter_Tall_Key_Light',
// 	'Keyboard/Esc_Key_Light',
// 	'Keyboard/F1_Key_Light',
// 	'Keyboard/F2_Key_Light',
// 	'Keyboard/F3_Key_Light',
// 	'Keyboard/F4_Key_Light',
// 	'Keyboard/F5_Key_Light',
// 	'Keyboard/F6_Key_Light',
// 	'Keyboard/F7_Key_Light',
// 	'Keyboard/F8_Key_Light',
// 	'Keyboard/F9_Key_Light',
// 	'Keyboard/F_Key_Light',
// 	'Keyboard/G_Key_Light',
// 	'Keyboard/H_Key_Light',
// 	'Keyboard/Home_Key_Light',
// 	'Keyboard/I_Key_Light',
// 	'Keyboard/Insert_Key_Light',
// 	'Keyboard/J_Key_Light',
// 	'Keyboard/K_Key_Light',
// 	'Keyboard/L_Key_Light',
// 	'Keyboard/M_Key_Light',
// 	'Keyboard/Mark_Left_Key_Light',
// 	'Keyboard/Mark_Right_Key_Light',
// 	'Keyboard/Minus_Key_Light',
// 	'Keyboard/Mouse_Left_Key_Light',
// 	'Keyboard/Mouse_Middle_Key_Light',
// 	'Keyboard/Mouse_Right_Key_Light',
// 	'Keyboard/Mouse_Simple_Key_Light',
// 	'Keyboard/N_Key_Light',
// 	'Keyboard/Num_Lock_Key_Light',
// 	'Keyboard/O_Key_Light',
// 	'Keyboard/P_Key_Light',
// 	'Keyboard/Page_Down_Key_Light',
// 	'Keyboard/Page_Up_Key_Light',
// 	'Keyboard/Plus_Key_Light',
// 	'Keyboard/Plus_Tall_Key_Light',
// 	'Keyboard/Print_Screen_Key_Light',
// 	'Keyboard/Q_Key_Light',
// 	'Keyboard/Question_Key_Light',
// 	'Keyboard/Quote_Key_Light',
// 	'Keyboard/R_Key_Light',
// 	'Keyboard/S_Key_Light',
// 	'Keyboard/Semicolon_Key_Light',
// 	'Keyboard/Shift_Alt_Key_Light',
// 	'Keyboard/Shift_Key_Light',
// 	'Keyboard/Slash_Key_Light',
// 	'Keyboard/Space_Key_Light',
// 	'Keyboard/T_Key_Light',
// 	'Keyboard/Tab_Key_Light',
// 	'Keyboard/Tilda_Key_Light',
// 	'Keyboard/U_Key_Light',
// 	'Keyboard/V_Key_Light',
// 	'Keyboard/W_Key_Light',
// 	'Keyboard/Win_Key_Light',
// 	'Keyboard/X_Key_Light',
// 	'Keyboard/Y_Key_Light',
// 	'Keyboard/Z_Key_Light',
// 	'PS5/PS5_Circle',
// 	'PS5/PS5_Cross',
// 	'PS5/PS5_Dpad',
// 	'PS5/PS5_Dpad_Down',
// 	'PS5/PS5_Dpad_Left',
// 	'PS5/PS5_Dpad_Right',
// 	'PS5/PS5_Dpad_Up',
// 	'PS5/PS5_L1',
// 	'PS5/PS5_L2',
// 	'PS5/PS5_Left_Stick',
// 	'PS5/PS5_Left_Stick_Click',
// 	'PS5/PS5_Microphone',
// 	'PS5/PS5_Options',
// 	'PS5/PS5_Options_Alt',
// 	'PS5/PS5_R1',
// 	'PS5/PS5_R2',
// 	'PS5/PS5_Right_Stick',
// 	'PS5/PS5_Right_Stick_Click',
// 	'PS5/PS5_Share',
// 	'PS5/PS5_Share_Alt',
// 	'PS5/PS5_Square',
// 	'PS5/PS5_Touch_Pad',
// 	'PS5/PS5_Triangle',
// 	'Xbox Series/XboxSeriesX_A',
// 	'Xbox Series/XboxSeriesX_B',
// 	'Xbox Series/XboxSeriesX_Dpad',
// 	'Xbox Series/XboxSeriesX_Dpad_Down',
// 	'Xbox Series/XboxSeriesX_Dpad_Left',
// 	'Xbox Series/XboxSeriesX_Dpad_Right',
// 	'Xbox Series/XboxSeriesX_Dpad_Up',
// 	'Xbox Series/XboxSeriesX_LB',
// 	'Xbox Series/XboxSeriesX_LT',
// 	'Xbox Series/XboxSeriesX_Left_Stick',
// 	'Xbox Series/XboxSeriesX_Left_Stick_Click',
// 	'Xbox Series/XboxSeriesX_Menu',
// 	'Xbox Series/XboxSeriesX_RB',
// 	'Xbox Series/XboxSeriesX_RT',
// 	'Xbox Series/XboxSeriesX_Right_Stick',
// 	'Xbox Series/XboxSeriesX_Right_Stick_Click',
// 	'Xbox Series/XboxSeriesX_Share',
// 	'Xbox Series/XboxSeriesX_View',
// 	'Xbox Series/XboxSeriesX_X',
// 	'Xbox Series/XboxSeriesX_Y',
// 	'Keyboard/F10_Key_Light',
// 	'Keyboard/F11_Key_Light',
// 	'Keyboard/F12_Key_Light',
// ] as const
// const keys
// = {
// 	Digit0: 'Keyboard/0_Key_Light',
// 	F10: 'Keyboard/F10_Key_Light',
// 	F11: 'Keyboard/F11_Key_Light',
// 	F12: 'Keyboard/F12_Key_Light',
// 	Digit1: 'Keyboard/1_Key_Light',
// 	Digit2: 'Keyboard/2_Key_Light',
// 	Digit3: 'Keyboard/3_Key_Light',
// 	Digit4: 'Keyboard/4_Key_Light',
// 	Digit5: 'Keyboard/5_Key_Light',
// 	Digit6: 'Keyboard/6_Key_Light',
// 	Digit7: 'Keyboard/7_Key_Light',
// 	Digit8: 'Keyboard/8_Key_Light',
// 	Digit9: 'Keyboard/9_Key_Light',
// 	KeyA: 'Keyboard/A_Key_Light',
// 	AltLeft: 'Keyboard/Alt_Key_Light',
// 	ArrowDown: 'Keyboard/Arrow_Down_Key_Light',
// 	ArrowLeft: 'Keyboard/Arrow_Left_Key_Light',
// 	ArrowRight: 'Keyboard/Arrow_Right_Key_Light',
// 	ArrowUp: 'Keyboard/Arrow_Up_Key_Light',
// 	Escape: 'Keyboard/Print_Screen_Key_Light',
// 	KeyB: 'Keyboard/B_Key_Light',
// 	ShiftLeft: 'Keyboard/Backspace_Alt_Key_Light',
// 	Backspace: 'Keyboard/Backspace_Key_Light',
// 	BracketLeft: 'Keyboard/Bracket_Left_Key_Light',
// 	BracketRight: 'Keyboard/Bracket_Right_Key_Light',
// 	KeyC: 'Keyboard/C_Key_Light',
// 	CapsLock: 'Keyboard/Caps_Lock_Key_Light',
// 	MetaLeft: 'Keyboard/Win_Key_Light',
// 	ControlLeft: 'Keyboard/Ctrl_Key_Light',
// 	KeyD: 'Keyboard/D_Key_Light',
// 	Delete: 'Keyboard/Del_Key_Light',
// 	KeyE: 'Keyboard/E_Key_Light',
// 	End: 'Keyboard/End_Key_Light',
// 	Enter: 'Keyboard/Enter_Tall_Key_Light',
// 	F1: 'Keyboard/F1_Key_Light',
// 	F2: 'Keyboard/F2_Key_Light',
// 	F3: 'Keyboard/F3_Key_Light',
// 	F4: 'Keyboard/F4_Key_Light',
// 	F5: 'Keyboard/F5_Key_Light',
// 	F6: 'Keyboard/F6_Key_Light',
// 	F7: 'Keyboard/F7_Key_Light',
// 	F8: 'Keyboard/F8_Key_Light',
// 	F9: 'Keyboard/F9_Key_Light',
// 	KeyF: 'Keyboard/F_Key_Light',
// 	KeyG: 'Keyboard/G_Key_Light',
// 	KeyH: 'Keyboard/H_Key_Light',
// 	Home: 'Keyboard/Home_Key_Light',
// 	KeyI: 'Keyboard/I_Key_Light',
// 	KeyJ: 'Keyboard/J_Key_Light',
// 	KeyK: 'Keyboard/K_Key_Light',
// 	KeyL: 'Keyboard/L_Key_Light',
// 	KeyM: 'Keyboard/M_Key_Light',
// 	Comma: 'Keyboard/Mark_Left_Key_Light',
// 	Period: 'Keyboard/Mark_Right_Key_Light',
// 	Minus: 'Keyboard/Minus_Key_Light',
// 	KeyN: 'Keyboard/N_Key_Light',
// 	KeyO: 'Keyboard/O_Key_Light',
// 	KeyP: 'Keyboard/P_Key_Light',
// 	PageDown: 'Keyboard/Page_Down_Key_Light',
// 	PageUp: 'Keyboard/Page_Up_Key_Light',
// 	Equal: 'Keyboard/Plus_Tall_Key_Light',
// 	KeyQ: 'Keyboard/Q_Key_Light',
// 	Slash: 'Keyboard/Question_Key_Light',
// 	Quote: 'Keyboard/Quote_Key_Light',
// 	KeyR: 'Keyboard/R_Key_Light',
// 	KeyS: 'Keyboard/S_Key_Light',
// 	Semicolon: 'Keyboard/Semicolon_Key_Light',
// 	ShiftRight: 'Keyboard/Shift_Key_Light',
// 	Backslash: 'Keyboard/Slash_Key_Light',
// 	Space: 'Keyboard/Space_Key_Light',
// 	KeyT: 'Keyboard/T_Key_Light',
// 	Tab: 'Keyboard/Tab_Key_Light',
// 	Backquote: 'Keyboard/Tilda_Key_Light',
// 	KeyU: 'Keyboard/U_Key_Light',
// 	KeyV: 'Keyboard/V_Key_Light',
// 	KeyW: 'Keyboard/W_Key_Light',
// 	KeyX: 'Keyboard/X_Key_Light',
// 	KeyY: 'Keyboard/Y_Key_Light',
// 	KeyZ: 'Keyboard/Z_Key_Light',
// }
export const keys: Record<string, string> = {
	'0': 'Keyboard/0_Key_Light',
	'1': 'Keyboard/1_Key_Light',
	'2': 'Keyboard/2_Key_Light',
	'3': 'Keyboard/3_Key_Light',
	'4': 'Keyboard/4_Key_Light',
	'5': 'Keyboard/5_Key_Light',
	'6': 'Keyboard/6_Key_Light',
	'7': 'Keyboard/7_Key_Light',
	'8': 'Keyboard/8_Key_Light',
	'9': 'Keyboard/9_Key_Light',
	'F10': 'Keyboard/F10_Key_Light',
	'F11': 'Keyboard/F11_Key_Light',
	'F12': 'Keyboard/F12_Key_Light',
	'a': 'Keyboard/A_Key_Light',
	'Shift': 'Keyboard/Shift_Key_Light',
	'ArrowDown': 'Keyboard/Arrow_Down_Key_Light',
	'ArrowLeft': 'Keyboard/Arrow_Left_Key_Light',
	'ArrowRight': 'Keyboard/Arrow_Right_Key_Light',
	'ArrowUp': 'Keyboard/Arrow_Up_Key_Light',
	'b': 'Keyboard/B_Key_Light',
	'Backspace': 'Keyboard/Backspace_Key_Light',
	'[': 'Keyboard/Bracket_Left_Key_Light',
	']': 'Keyboard/Bracket_Right_Key_Light',
	'c': 'Keyboard/C_Key_Light',
	'CapsLock': 'Keyboard/Caps_Lock_Key_Light',
	'Meta': 'Keyboard/Win_Key_Light',
	'Control': 'Keyboard/Ctrl_Key_Light',
	'd': 'Keyboard/D_Key_Light',
	'Delete': 'Keyboard/Del_Key_Light',
	'e': 'Keyboard/E_Key_Light',
	'End': 'Keyboard/End_Key_Light',
	'Enter': 'Keyboard/Enter_Key_Light',
	'Escape': 'Keyboard/Esc_Key_Light',
	'F1': 'Keyboard/F1_Key_Light',
	'F2': 'Keyboard/F2_Key_Light',
	'F3': 'Keyboard/F3_Key_Light',
	'F4': 'Keyboard/F4_Key_Light',
	'F5': 'Keyboard/F5_Key_Light',
	'F6': 'Keyboard/F6_Key_Light',
	'F7': 'Keyboard/F7_Key_Light',
	'F8': 'Keyboard/F8_Key_Light',
	'F9': 'Keyboard/F9_Key_Light',
	'f': 'Keyboard/F_Key_Light',
	'g': 'Keyboard/G_Key_Light',
	'h': 'Keyboard/H_Key_Light',
	'Home': 'Keyboard/Home_Key_Light',
	'i': 'Keyboard/I_Key_Light',
	'j': 'Keyboard/J_Key_Light',
	'k': 'Keyboard/K_Key_Light',
	'l': 'Keyboard/L_Key_Light',
	'm': 'Keyboard/M_Key_Light',
	'<': 'Keyboard/Mark_Left_Key_Light',
	'>': 'Keyboard/Mark_Right_Key_Light',
	'-': 'Keyboard/Minus_Key_Light',
	'n': 'Keyboard/N_Key_Light',
	'o': 'Keyboard/O_Key_Light',
	'p': 'Keyboard/P_Key_Light',
	'PageDown': 'Keyboard/Page_Down_Key_Light',
	'PageUp': 'Keyboard/Page_Up_Key_Light',
	'+': 'Keyboard/Plus_Tall_Key_Light',
	'q': 'Keyboard/Q_Key_Light',
	'?': 'Keyboard/Question_Key_Light',
	'\'': 'Keyboard/Quote_Key_Light',
	'r': 'Keyboard/R_Key_Light',
	's': 'Keyboard/S_Key_Light',
	';': 'Keyboard/Semicolon_Key_Light',
	'#': 'Keyboard/Slash_Key_Light',
	' ': 'Keyboard/Space_Key_Light',
	't': 'Keyboard/T_Key_Light',
	'Tab': 'Keyboard/Tab_Key_Light',
	'~': 'Keyboard/Tilda_Key_Light',
	'u': 'Keyboard/U_Key_Light',
	'v': 'Keyboard/V_Key_Light',
	'w': 'Keyboard/W_Key_Light',
	'x': 'Keyboard/X_Key_Light',
	'y': 'Keyboard/Y_Key_Light',
	'z': 'Keyboard/Z_Key_Light',
}
export const metaKeys: Record<string, string> = {
	Enter: 'Enter',
	CapsLock: 'CapsLock',
	ShiftLeft: 'Shift',
	ShiftRight: 'Shift',
	ArrowRight: 'ArrowRight',
	ArrowDown: 'ArrowDown',
	ArrowLeft: 'ArrowLeft',
	ArrowUp: 'ArrowUp',
	ControlRight: 'Control',
	AltRight: 'AltGraph',
	Space: ' ',
	AltLeft: 'Alt',
	ControlLeft: 'Control',
	Tab: 'Tab',
	Backspace: 'Backspace',
	Escape: 'Escape',
	F1: 'F1',
	F2: 'F2',
	F3: 'F3',
	F4: 'F4',
	F5: 'F5',
	F6: 'F6',
	F7: 'F7',
	F8: 'F8',
	F9: 'F9',
	F10: 'F10',
	F11: 'F11',
	F12: 'F12',
	MetaLeft: 'Meta',
}