export type buttons = `texture` | `texture`
export type characters = `Armabee` | `Armabee_Evolved` | `BunnydAnim` | `cauldron` | `Panda`
export type crops = `Beet_1` | `Beet_2` | `Beet_3` | `Beet_4` | `Beet_Crop` | `Carrot_1` | `Carrot_2` | `Carrot_3` | `Carrot_4` | `Carrot_Crop` | `Mushroom_1` | `Mushroom_2` | `Mushroom_3` | `Mushroom_4` | `Mushroom_Crop`
export type fonts = `GrapeSoda` | `NanoPlus`
export type grass = `SM_Env_Grass_01` | `SM_Env_Grass_02`
export type icons = `basket-shopping-solid` | `circle-check-solid` | `circle-xmark-solid` | `list-check-solid` | `pause-solid` | `xmark-solid`
export type items = `beet` | `beet_seeds` | `carrot` | `carrot_seeds` | `carrot_soup` | `honey` | `honey_glazed_carrot` | `mushroom` | `roasted_carrot`
export type levels = `data` | `levels`
export type models = `Bulliten` | `BunnyOvenPacked` | `Chest` | `gardenPlot1` | `gardenPlot2` | `gardenPlot3` | `Lamp` | `Lamp2` | `plantedHole` | `Rock_1` | `Rock_2` | `Rock_3` | `Rock_4` | `Rock_5` | `Rock_6` | `Rock_7` | `Rock_Moss_1` | `Rock_Moss_2` | `Rock_Moss_3` | `Rock_Moss_4` | `Rock_Moss_5` | `Rock_Moss_6` | `Rock_Moss_7` | `SM_Env` | `SM_Env` | `SM_Env_Flower_01` | `SM_Env_Flower_02` | `SM_Env_Flower_03` | `SM_Env_Flower_04` | `SM_Env_Flower_05` | `SM_Env_Flower_06` | `SM_Env_Flower_07` | `SM_Env_Flower_08` | `SM_Env_Grass_01` | `SM_Env_Grass_02` | `StoneOven` | `Stove1` | `WoodenSign` | `WoodenSign2` | `WoodLog`
export type particles = `star_07`
export type skybox = `CloudyCrown_Midday_Back` | `CloudyCrown_Midday_Down` | `CloudyCrown_Midday_Front` | `CloudyCrown_Midday_Left` | `CloudyCrown_Midday_Right` | `CloudyCrown_Midday_Up`
export type trees = `Low_Poly_Forest_treeTall` | `Low_Poly_Forest_treeTall` | `Low_Poly_Forest_treeTall01` | `Low_Poly_Forest_treeTall02` | `Low_Poly_Forest_treeTall03` | `Low_Poly_Forest_treeTall04`
export type trees2 = `CommonTree_1` | `CommonTree_2` | `CommonTree_3` | `CommonTree_4` | `CommonTree_5` | `PineTree_1` | `PineTree_2` | `PineTree_3` | `PineTree_4` | `PineTree_5`
